service: acceptessa2-administration-login
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action: [lambda:Invoke]
      Resource:
        - Fn::Join: [ ":", ["arn:aws:lambda", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "function", "acceptessa2-mail-sender"]]
    - Effect: Allow
      Action: [dynamodb:GetItem, dynamodb:PutItem, dynamodb:DeleteItem]
      Resource:
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/acceptessa2-login-token"]]
    - Effect: Allow
      Action: [cloudfront:ListKeyGroups]
      Resource: "*"

#  environment:
#    variable1: value1
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  check:
    handler: handler.check
    events:
     - httpApi:
         path: /check
         method: "*"

  login:
    handler: handler.login
    events:
     - httpApi:
         path: /login
         method: GET
