service: acceptessa2-administration-login
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1

#  environment:
#    variable1: value1
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello:
    handler: handler.hello
    events:
     - httpApi:
         path: /{proxy+}
         method: GET
#    environment:
#      variable2: value2
